/**
 * @zairn/geo-drop Type Definitions
 * Types for location-bound data drops
 */

// =====================
// Drop types
// =====================
export type DropVisibility = 'public' | 'friends' | 'private' | 'password';
export type DropContentType = 'text' | 'image' | 'audio' | 'video' | 'file' | 'nft';
export type DropStatus = 'active' | 'expired' | 'claimed' | 'deleted';

// =====================
// IPFS
// =====================
export interface IpfsConfig {
  gateway: string;
  /** Fallback gateways for fetch (tried in order if primary fails) */
  fallbackGateways?: string[];
  pinningService?: 'pinata' | 'web3storage' | 'custom';
  pinningApiKey?: string;
  pinningApiSecret?: string;
  customPinningUrl?: string;
  /** Max upload size in bytes (default: 10MB) */
  maxUploadSize?: number;
}

export interface IpfsUploadResult {
  cid: string;
  size: number;
  url: string;
}

// =====================
// Encryption
// =====================
export interface EncryptedPayload {
  ciphertext: string;
  iv: string;
  salt: string;
}

// =====================
// Location proof methods
// =====================

/**
 * Proof method type
 * - gps: GPS coordinates (default)
 * - secret: ID/secret matching (front-end sends an ID obtained via QR, BLE, WiFi, NFC, etc.)
 * - ar: Image feature-based location verification
 * - zkp: Zero-knowledge proof of proximity (Groth16) — proves location without revealing coordinates
 * - zkp-region: Zero-knowledge proof of polygon containment (Groth16) — proves inside a region
 * - custom: Fully custom verifier
 */
export type ProofMethodType = 'gps' | 'secret' | 'ar' | 'zkp' | 'zkp-region' | 'custom';

/**
 * Proof requirements set on a drop
 * When multiple are specified, mode (all/any) switches between AND/OR
 */
export interface ProofRequirement {
  /** Proof method type */
  method: ProofMethodType;
  /**
   * Method-specific parameters
   * - gps: {} (default; controlled by unlock_radius_meters)
   * - secret: { secret: string; label?: string } — secret obtained on-site (via QR/BLE/WiFi/NFC etc., acquisition method is up to the front-end)
   * - ar: { reference_embedding?: number[]; reference_embeddings?: number[][]; similarity_threshold?: number; max_age_seconds?: number } — DINOv2 feature vector(s). Multiple embeddings for multi-angle matching (client picks max similarity). max_age_seconds rejects stale captures
   * - zkp: { verification_key: object; artifacts_url?: string; policy_version?: string; epoch?: string|number; server_nonce?: string; drop_id?: string } — Groth16 verification key for Zairn-ZKP. Optional context fields bind proofs to a drop/session statement
   * - zkp-region: { verification_key: object; polygon: {lat: number; lon: number}[]; artifacts_url?: string; policy_version?: string; epoch?: string|number; server_nonce?: string; drop_id?: string } — polygon containment proof
   * - custom: { verifier_id: string; [key: string]: unknown } — parameters passed to a custom verifier
   */
  params: Record<string, unknown>;
  /** Whether this method is required or optional (default: true) */
  required?: boolean;
}

/**
 * Proof configuration for a drop
 */
export interface ProofConfig {
  /**
   * Verification mode
   * - 'all': All required proofs must be satisfied (AND)
   * - 'any': Any single proof is sufficient (OR)
   * Default: 'all'
   */
  mode: 'all' | 'any';
  /** List of proof requirements */
  requirements: ProofRequirement[];
}

/**
 * Proof response submitted by a user
 */
export interface ProofSubmission {
  /** Proof method type */
  method: ProofMethodType;
  /**
   * Method-specific response data
   * - gps: { lat: number; lon: number; accuracy: number }
   * - secret: { secret: string } — secret obtained on-site (acquisition method does not matter)
   * - ar: { image: string; captured_at?: string; image_width?: number; image_height?: number } — base64 of captured image. captured_at (ISO 8601) for freshness check. Dimensions for screenshot detection
   * - zkp: { proof: Groth16Proof; publicSignals: string[]; statement?: ZkStatementBinding } — ZK proximity proof generated by snarkjs, optionally including the resolved public statement binding
   * - zkp-region: { proof: Groth16Proof; publicSignals: string[]; statement?: ZkStatementBinding } — ZK polygon containment proof
   * - custom: { verifier_id: string; [key: string]: unknown }
   */
  data: Record<string, unknown>;
}

/**
 * Verification result for a single proof
 */
export interface ProofResult {
  method: ProofMethodType;
  verified: boolean;
  /** Verification details (method-specific) */
  details: Record<string, unknown>;
}

/**
 * Combined result of all verifications
 */
export interface VerificationResult {
  verified: boolean;
  /** Result for each proof method */
  proofs: ProofResult[];
  /** GPS-based location proof (when GPS verification is included) */
  location_proof?: LocationProof;
  timestamp: string;
}

/**
 * Custom verifier function type
 * Interface for SDK consumers to register custom verification logic
 */
export type ProofVerifier = (
  requirement: ProofRequirement,
  submission: ProofSubmission,
  drop: GeoDrop
) => Promise<ProofResult> | ProofResult;

// =====================
// Location proof
// =====================
export interface LocationProof {
  user_id: string;
  lat: number;
  lon: number;
  accuracy: number;
  timestamp: string;
  geohash: string;
  distance_to_target: number;
  verified: boolean;
}

// =====================
// Drop
// =====================
export interface GeoDrop {
  id: string;
  creator_id: string;
  // Location
  lat: number;
  lon: number;
  geohash: string;
  unlock_radius_meters: number;
  // Content
  title: string;
  description: string | null;
  content_type: DropContentType;
  ipfs_cid: string | null;
  encrypted_content: string | null;
  encrypted: boolean;
  encryption_salt: string | null;
  // Access control
  visibility: DropVisibility;
  password_hash: string | null;
  max_claims: number | null;
  claim_count: number;
  // Location proof
  proof_config: ProofConfig | null;
  // Expiration
  expires_at: string | null;
  status: DropStatus;
  // Metadata
  preview_url: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
  // Persistence (for DB-independent recovery, optional)
  persistence_level?: PersistenceLevel;
  metadata_cid?: string;
  chain_tx_hash?: string;
}

export interface GeoDropCreate {
  title: string;
  description?: string;
  content_type: DropContentType;
  lat: number;
  lon: number;
  unlock_radius_meters?: number;
  visibility?: DropVisibility;
  password?: string;
  max_claims?: number;
  expires_at?: Date;
  metadata?: Record<string, unknown>;
  /** User IDs to share a private drop with */
  shared_with?: string[];
  /** Proof configuration (defaults to GPS only when unspecified) */
  proof_config?: ProofConfig;
  /** Persistence level (uses GeoDropOptions default when unspecified) */
  persistence?: PersistenceLevel;
  /** Secret for metadata encryption (recommended for private/password drops) */
  recoverySecret?: string;
}

// =====================
// Private sharing
// =====================
export interface DropShare {
  drop_id: string;
  user_id: string;
  created_at: string;
}

// =====================
// Claim (collection record)
// =====================
export interface DropClaim {
  id: string;
  drop_id: string;
  user_id: string;
  lat: number;
  lon: number;
  distance_meters: number;
  proof_results: ProofResult[] | null;
  claimed_at: string;
}

// =====================
// Discovery (nearby drops)
// =====================
export interface NearbyDrop {
  drop: GeoDrop;
  distance_meters: number;
  can_unlock: boolean;
}

// =====================
// Stats
// =====================
export interface DropStats {
  total_created: number;
  total_claimed: number;
  total_active: number;
  unique_locations: number;
}

// =====================
// NFT extension (future use)
// =====================
export interface NftMetadata {
  name: string;
  description: string;
  image: string;
  attributes: {
    trait_type: string;
    value: string | number;
  }[];
  geo_drop: {
    lat: number;
    lon: number;
    geohash: string;
    drop_id: string;
    ipfs_cid: string;
  };
}

// =====================
// Persistence (DB-independent recovery)
// =====================

/**
 * Persistence level
 * - db-only: DB storage only (default, free)
 * - ipfs: Metadata also pinned to IPFS (recoverable even if DB is lost, requires ongoing pinning)
 * - onchain: Metadata CID recorded on-chain (implicitly pins to IPFS as well)
 * - ipfs+onchain: Explicitly both
 */
export type PersistenceLevel = 'db-only' | 'ipfs' | 'onchain' | 'ipfs+onchain';

/**
 * Abstract interface for an EVM signer
 * Can be adapted for either ethers.js Signer or viem WalletClient
 */
export interface EvmSigner {
  getAddress(): Promise<string>;
  sendTransaction(tx: {
    to: string;
    data: string;
    value?: string;
  }): Promise<{ hash: string; wait(confirmations?: number): Promise<{ status: number }> }>;
}

/**
 * Chain configuration
 */
export interface ChainConfig {
  /** EVM JSON-RPC endpoint */
  rpcUrl: string;
  /** Deployed GeoDropRegistry contract address */
  registryAddress: string;
  /** Signer (required for write operations; optional for read-only) */
  signer?: EvmSigner;
  /** Chain ID (optional, for logging) */
  chainId?: number;
  /** Number of confirmations to wait (default: 2 for L1, 1 for L2) */
  confirmations?: number;
}

/**
 * Persistence configuration
 */
export interface PersistenceConfig {
  level: PersistenceLevel;
  chain?: ChainConfig;
  /** Whether to fail drop creation if persistence fails (default: false) */
  strict?: boolean;
}

/**
 * Metadata document stored on IPFS
 * This document alone is sufficient to decrypt content even if DB is lost
 */
export interface DropMetadataDocumentV1 {
  version: 1;
  dropId: string;
  geohash: string;
  contentCid: string;
  encryptionSalt: string;
  unlockRadiusMeters: number;
  contentType: DropContentType;
  title: string;
  proofConfig: ProofConfig | null;
  createdAt: string;
  encrypted?: boolean;
}

export interface DropMetadataDocumentV2 {
  version: 2;
  dropId: string;
  geohash: string;
  contentCid: string;
  encryptionSalt: string;
  unlockRadiusMeters: number;
  contentType: DropContentType;
  title: string;
  proofConfig: ProofConfig | null;
  createdAt: string;
  encrypted?: boolean;
  /** Key derivation version (1 or 2). Required for decryption. */
  keyDerivationVersion: 1 | 2;
  /** Encryption algorithm identifier for future migration */
  encryptionAlgorithm: 'aes-256-gcm';
  /** PBKDF2 iteration count (for key stretching migration) */
  pbkdf2Iterations: number;
  /** Pinning providers used (for monitoring/renewal) */
  pinningProviders?: string[];
  /** Content size in bytes (for storage accounting) */
  contentSizeBytes?: number;
  /** Server secret version used to encrypt (for recovery decryption) */
  serverSecretVersion?: number;
}

/** Union type for all metadata versions */
export type DropMetadataDocument = DropMetadataDocumentV1 | DropMetadataDocumentV2;

/**
 * Result of a persistence operation
 */
export interface PersistenceResult {
  level: PersistenceLevel;
  metadataCid?: string;
  txHash?: string;
  chainId?: number;
  pinResults?: Array<{ provider: string; ok: boolean; error?: string }>;
}

/**
 * Drop information recovered independently of DB
 */
export interface RecoveredDrop {
  metadata: DropMetadataDocument;
  metadataCid: string;
  source: 'ipfs' | 'onchain';
}

// =====================
// Location Trust Scoring
// =====================

/** A single location point used for trust scoring */
export interface LocationPoint {
  lat: number;
  lon: number;
  accuracy: number | null;
  timestamp: string;
  speed?: number | null;
}

/** Result of trust scoring */
export interface TrustScoreResult {
  /** Overall trust score: 0.0 (untrusted) to 1.0 (fully trusted) */
  trustScore: number;
  /** True when trustScore < 0.3 */
  spoofingSuspected: boolean;
  /** Breakdown of individual signal scores */
  signals: {
    movementPlausibility: number;
    accuracyAnomaly: number;
    temporalConsistency: number;
  };
}

/** Action gate thresholds */
export interface TrustThresholds {
  /** Score >= this: proceed normally (default 0.7) */
  proceed: number;
  /** Score >= this but < proceed: step-up verification (default 0.3) */
  stepUp: number;
}

// =====================
// Trust scoring V2 (RAIM-style integrity)
// =====================

/** A single raw GPS fix for RAIM-style consistency analysis */
export interface GpsFix {
  lat: number;
  lon: number;
  accuracy: number;
  timestamp: string;
}

/** Network-derived position hint for cross-check */
export interface NetworkHint {
  lat: number;
  lon: number;
  /** Estimated accuracy in meters (typically 1–50 km for IP geolocation) */
  accuracy: number;
  source: 'ip' | 'cell' | 'wifi';
}

/** Additional context for V2 trust scoring */
export interface TrustContext {
  recentFixes?: GpsFix[];
  networkHint?: NetworkHint;
}

/** Extended trust score result with V2 signals */
export interface TrustScoreResultV2 extends TrustScoreResult {
  signals: TrustScoreResult['signals'] & {
    fixConsistency?: number;
    networkConsistency?: number;
  };
}

// =====================
// Step-up verification
// =====================

/** Returned by unlockDrop when trust score is in the step-up range */
export interface StepUpRequired {
  type: 'step-up-required';
  /** The trust score that triggered step-up (between stepUp and proceed thresholds) */
  trustScore: number;
  /** Human-readable reason for the step-up request */
  reason: string;
  /** Proof methods available for step-up verification on this drop */
  availableMethods: ProofMethodType[];
  /** The drop ID being unlocked */
  dropId: string;
}

/** Successful unlock result */
export interface UnlockSuccess {
  type: 'success';
  content: string;
  claim: DropClaim;
  verification: VerificationResult;
}

/** Union type for unlockDrop return value */
export type UnlockResult = UnlockSuccess | StepUpRequired;

// =====================
// SDK
// =====================
export interface GeoDropOptions {
  supabaseUrl: string;
  supabaseAnonKey: string;
  ipfs?: IpfsConfig;
  /** Initial custom proof verifiers to register */
  verifiers?: Record<string, ProofVerifier>;
  /**
   * Image proof Edge Function URL
   * Defaults to supabaseUrl + '/functions/v1/image-proof' when unspecified
   */
  imageProofUrl?: string;
  /**
   * Enable server-side unlock via Edge Function (recommended for production).
   * When true, unlockDrop calls the unlock-drop Edge Function instead of
   * decrypting client-side, so encryption keys never reach the client.
   * Defaults to supabaseUrl + '/functions/v1/unlock-drop'
   */
  serverUnlock?: boolean | string;
  /**
   * IPFS proxy Edge Function URL.
   * When set, IPFS operations go through the proxy and API keys stay server-side.
   * Defaults to supabaseUrl + '/functions/v1/ipfs-proxy' when serverUnlock is enabled.
   */
  ipfsProxyUrl?: string;
  /** Persistence configuration */
  persistence?: PersistenceConfig;
  /**
   * Server-side encryption secret(s) for location key derivation.
   *
   * Option A: Single secret (backward compatible)
   *   encryptionSecret: 'my-secret'
   *
   * Option B: Versioned secret map (enables rotation)
   *   encryptionSecrets: { 1: 'old-secret', 2: 'new-secret' }
   *   currentSecretVersion: 2
   *
   * When serverUnlock is disabled, at least one secret is REQUIRED
   * for production — without it, encryption keys are predictable
   * from publicly-visible DB columns.
   *
   * Set allowInsecureNoSecret: true to suppress the error (dev only).
   */
  encryptionSecret?: string;
  /** Versioned secret map for key rotation. Keys are version numbers. */
  encryptionSecrets?: Record<number, string>;
  /** Which secret version to use for NEW drops (default: 1 or max key in encryptionSecrets) */
  currentSecretVersion?: number;
  /** Allow SDK to run without encryption secret (dev/testing only) */
  allowInsecureNoSecret?: boolean;
  /**
   * SBPP: encrypted search configuration for Search-Bound Proximity Proofs.
   * When set, enables findNearbyDropsSbpp() and initSearchSession().
   */
  encryptedSearchConfig?: { searchKey: string; precisionLevels?: number[] };
}

export interface GeoDropSDK {
  // Drop CRUD
  createDrop: (data: GeoDropCreate, content: File | Blob | string) => Promise<GeoDrop>;
  getDrop: (dropId: string) => Promise<GeoDrop | null>;
  getMyDrops: (options?: { status?: DropStatus; limit?: number }) => Promise<GeoDrop[]>;
  deleteDrop: (dropId: string) => Promise<void>;

  // Discovery & unlock
  findNearbyDrops: (lat: number, lon: number, radiusMeters?: number) => Promise<NearbyDrop[]>;
  unlockDrop: (dropId: string, lat: number, lon: number, accuracy: number, password?: string, proofs?: ProofSubmission[]) => Promise<UnlockResult>;

  // Location proof
  getProofConfig: (dropId: string) => Promise<ProofConfig | null>;
  registerVerifier: (methodOrId: ProofMethodType | string, verifier: ProofVerifier) => void;

  // Image proof (server-side DINOv2)
  /** Extract feature vector from a reference image (used during drop creation) */
  extractImageEmbedding: (imageBase64: string) => Promise<{ embedding: number[]; dimensions: number }>;
  /** Compare a captured image against a drop's reference and verify (for debug/direct calls) */
  verifyImageProof: (imageBase64: string, dropId: string, threshold?: number) => Promise<{ verified: boolean; similarity: number }>;

  // Private sharing
  shareDrop: (dropId: string, userIds: string[]) => Promise<void>;
  unshareDrop: (dropId: string, userId: string) => Promise<void>;
  getSharedDrops: () => Promise<GeoDrop[]>;

  // Claims
  getDropClaims: (dropId: string) => Promise<DropClaim[]>;
  getMyClaims: (options?: { limit?: number }) => Promise<DropClaim[]>;

  // Stats
  getMyStats: () => Promise<DropStats>;

  // IPFS
  uploadToIpfs: (content: File | Blob | string) => Promise<IpfsUploadResult>;
  fetchFromIpfs: (cid: string) => Promise<string>;

  // Geofence verification
  verifyLocation: (dropId: string, lat: number, lon: number, accuracy: number) => Promise<LocationProof>;

  // Realtime
  subscribeNearbyDrops: (lat: number, lon: number, radiusMeters: number, onDrop: (drop: GeoDrop) => void) => import('@supabase/supabase-js').RealtimeChannel;

  // NFT metadata generation
  generateNftMetadata: (drop: GeoDrop, imageUrl?: string) => NftMetadata;

  // DB-independent recovery
  /** Recover directly from a metadata CID */
  recoverDrop: (metadataCid: string, recoverySecret?: string) => Promise<RecoveredDrop>;
  /** Search the on-chain index by location and recover */
  discoverDropsByLocation: (lat: number, lon: number, precision?: number) => Promise<RecoveredDrop[]>;
  /** Decrypt recovered drop content */
  decryptRecoveredDrop: (recovered: RecoveredDrop) => Promise<string>;

  // Key rotation
  /** Re-encrypt a drop from old secret version to new secret version */
  reEncryptDrop: (dropId: string, oldSecretVer: number, newSecretVer: number) => Promise<void>;
  /** Export encryption secrets as a password-encrypted backup blob */
  exportEncryptedSecrets: (masterPassword: string) => Promise<string>;
  /** Import encryption secrets from a backup blob */
  importEncryptedSecrets: (blob: string, masterPassword: string) => Promise<Record<number, string>>;

  // SBPP (Search-Bound Proximity Proofs)
  /** Initialize an SBPP search session. Returns a session with nonce for binding. */
  initSearchSession?: (ttlMs?: number) => { sessionId: string; nonce: string; createdAt: number; expiresAt: number };
  /** Find nearby drops using encrypted search tokens, bound to an SBPP session. */
  findNearbyDropsSbpp?: (lat: number, lon: number, radiusMeters: number, session: { sessionId: string; nonce: string; createdAt: number; expiresAt: number }) => Promise<NearbyDrop[]>;

  // Utilities
  encodeGeohash: (lat: number, lon: number, precision?: number) => string;
  decodeGeohash: (geohash: string) => { lat: number; lon: number };
  calculateDistance: (lat1: number, lon1: number, lat2: number, lon2: number) => number;
}
